### ISSUE TITLE
undefinedとnullの比較ルールを設定

### ISSUE THREAD

**Issue by sushichan044** [VirtualLiveLab/js-config#101]
nullとundefinedは、条件比較の文脈では同時に弾きたいので、`==`を使わせる

**Comment by sushi-chaaaan** [comment]
おそらく、nullとundefinedのどちらかの比較を検出したときに
`==null`か`==undefined`を強制させないといけない

**Comment by sushi-chaaaan** [comment]
`==null`に統一するのが丸そう

**Comment by sushichan044** [comment]
別にこのルールを作成しても、そこまで統一する嬉しさがないので作成しない
