### ISSUE TITLE
Astroなどからimportした型をtypescript-eslintが認識しない

### ISSUE THREAD

**Issue by sushichan044** [VirtualLiveLab/js-config#89]
https://github.com/ota-meshi/eslint-plugin-astro/issues/341
などにあるようにtypescript-eslintのparserは`.ts`ファイル以外から型情報を解釈できない。
代わりにIssue内で紹介されている`typescript-eslint-parser-for-extra-files`を利用することで解決を試みる。

**Comment by sushi-chaaaan** [comment]
思ったより厳しい

**Comment by sushi-chaaaan** [comment]
Flat Config環境下での`tseslint.config`に渡した際に想定した挙動にならない。
ESLint Config Inspectorなどで詳しく調べないとわからない

**Comment by sushichan044** [comment]
https://github.com/ota-meshi/typescript-eslint-parser-for-extra-files/issues/95 参考になりそう

**Comment by sushichan044** [comment]
closed by #288
